ViewTouch/viewtouch

- .travis.yml
add debian buster to the test matrix
> ci: add debian buster

- conf_file.cc
Always use locale "C". Some languages like de_DE and nb_NO use ',' as
decimal separator and '.' as thousand separator. The config file is
always written and read with the "C" locale
Please merge this commit before https://github.com/ViewTouch/viewtouch/pull/32
> conf: handle other locale settings

- print/print_main.cc
- use iostream
- use string
- use more const
- more resilient command line parsing
> print_main: modernize

- CMakeLists.txt
- tests/image_data/CMakeLists.txt
- tests/image_data/test_image_data.cc
just very basic test if the access function works
> tests: add image_data public function tests

- loader/loader_main.cc
- use std::string for global strings
- setupConnection: more std::string
- WriteArgList:
- rewrite with std::ofstream
- more verbose error messages
> vtpos: modernize WriteArgList

- conf_file.cc
- conf_file.hh
- main/manager.cc
- main/settings.cc
- tests/conf_file/test_conf_file.cc
rework the internal data structure of ConfFile. I hope to use it instead of KeyValueInput and KeyValueOutput file in `main/*` in the future
> Conf file rework

- external/date/README.md
- tests/time_info/test_time_info.cc
- time_info.cc
fix weekday calculation
also finish time_info unittest
> Time unit fix weekday

- main/manager.cc
- main/manager.hh
- main/terminal.hh
fix segmentation fault because of unsigned long to int conversion
> main: manager: fix segmenationfault on quick button press

- CMakeLists.txt
forwarding https://github.com/NeroBurner/viewtouch/pull/1 with a small fix and less verbose linking output
> Check x11 dependencies in CMake

- CMakeLists.txt
fixes https://github.com/ViewTouch/viewtouch/issues/72
> fix Freetype linking on older distributions

- CMakeLists.txt
- data_file.cc
- data_file.hh
- tests/data_file/CMakeLists.txt
- tests/data_file/test_data_file.cc
- utility.cc
- utility.hh
- add a comparison operator for Str == std::string
- add data_file Read for size_t
- add unit test for data_file read and writes
> Missing functions and data file tests

- loader/loader_main.cc
- main/manager.cc
little fixes when passing std::string to printf functions
> String passings

- data_file.cc
- data_file.hh
- main/credit.hh
- tests/data_file/test_data_file.cc
use strong types for read and write of data_file, fixes compilation on armhf and arm64
> data_file strongly typed byte lengths

- changelog.md
add a human readable change log
> log: add a basic changelog file

- .travis.yml
- CMakeLists.txt
- changelog.md
- ci/toolchains/clang-cxx11.cmake
- ci/toolchains/clang-cxx17.cmake
- ci/toolchains/clang-tidy.cmake
- main/check.cc
- main/manager.cc
- last fixes needed for clang support
- enable clang build in CI
- Clang and GCC have different warning flags
> Clang cxx17 support

- main/printer.cc
- main/printer.hh
- main/system.cc
- main/system.hh
- main/terminal.cc
- main/terminal.hh
little updates to use `bool` instead of `int`, more use of `const` keyword in functions and use more `std::string` members
> More const and std string

- CMakeLists.txt
fixes https://github.com/ViewTouch/viewtouch/issues/103
> Don't install date header files

- .github/workflows/linux-simple-builds.yml
Only different compiler versions are covered. Different distros like
Debian or other versions of Ubuntu are not covered.
Fixes: https://github.com/ViewTouch/viewtouch/issues/122
> Add github action linux simple builds using ubuntu-20.04

- changelog.md
- external/catch2/catch.hpp
Fixes: https://github.com/ViewTouch/viewtouch/issues/131
> Update embedded catch.hpp to v2.13.10 to fix Ubuntu 20.04 build

- changelog.md
- main/manager.cc
This PR resolves several critical issues preventing ViewTouch from starting properly, particularly on Raspberry Pi 5 ARM64 systems.
- **Problem**: `DownloadFile()` was writing URL strings to files instead of downloading actual content
- **Impact**: All bootstrap files (vt_data, menu.dat, tables.dat, zone_db.dat) were corrupted, causing "no zone_db" crashes
- **Fix**: Implemented proper curl request with `setOpt()` and `perform()` for actual file downloads
- **Added**: 30-second timeout and comprehensive error handling
- **Problem**: System would hang indefinitely during employee database cleanup on Raspberry Pi 5 ARM64
- **Impact**: Complete system freeze at startup, only affected Pi 5 due to different memory management
- **Fix**: Skip problematic `Purge()` when `employee.dat` doesn't …
> Fix critical system startup failures and Pi 5 platform-specific issues

- CMakeLists.txt
- changelog.md
- docs/MIGRATION_TO_XFT.md
- font_check.cc
- main/labels.cc
- main/manager.cc
- term/term_dialog.cc
- term/term_dialog.hh
- term/term_view.cc
- term/term_view.hh
✨ Summary
This pull request introduces major enhancements to the ViewTouch font system, focusing on modern font rendering, developer tooling, and streamlined configuration.
🚀 Key Improvements
✅ Migrated to Scalable Xft/Fontconfig Fonts
Replaces legacy bitmap font usage with scalable Xft fonts for modern compatibility and improved rendering.
🧪 Added: font_check Utility
Interactive tool to visually and programmatically verify all ViewTouch fonts.
Features:
Opens an X11 window displaying each font.
Logs status/results to the terminal.
Allows stepping through fonts using mouse click or key press.
📄 Added: Documentation
docs/MIGRATION_TO_XFT.md:
Complete migration guide for transitioning to scalable Xft/Fontconfig fonts.
Includes font installation, troubleshooting steps, and integration into …
> Pull Request: Xft Font System Improvements, Interactive Font Test Utility, and Documentation

- changelog.md
- main/drawer.cc
- main/employee.cc
- main/locale.cc
- main/locale.hh
- main/manager.cc
- main/remote_printer.cc
- main/system.cc
- main/system.hh
- remote_link.cc
- term/term_view.cc
- zone/expense_zone.cc
- zone/phrase_zone.cc
- zone/user_edit_zone.cc
This pull request addresses critical stability issues and improves printer connectivity in ViewTouch.
- **SIGPIPE Crash Resolution**: Fixed critical crash when ViewTouch loses connection to vtpos daemon
- Added graceful handling of broken pipe errors in `CharQueue::Write()` method
- Prevents application crash when server connection is lost unexpectedly
- Returns -1 instead of crashing on `EPIPE` errors during socket writes
- **Employee Record Management Crashes**: Fixed multiple crash scenarios in employee management
- Added comprehensive null checks in `UserEditZone::SaveRecord()`
- Enhanced error handling in `UserDB::NewUser()` for memory allocation failures
- Fixed null pointer access during form field processing
- Safe handling of empty or corrupted employee data structures
- …
> Fix critical crashes and improve printer connectivity

- LICENSE
- README.md
- SECURITY.md
This PR updates the project documentation to meet modern standards and completes the previously unfinished LICENSE file setup.
- **Modern Security Policy**: Updated from basic template to comprehensive security policy following current industry best practices
- **Accurate Version Information**: Updated supported versions to reflect current ViewTouch version (21.05.x)
- **Proper Contact Information**: Added correct contact details (gene@viewtouch.com, 541-515-5913)
- **Vulnerability Reporting**: Added detailed guidelines for responsible disclosure
- **Response Timeline**: Committed to 48-hour initial response and 7-day status updates
- **Security Best Practices**: Added recommendations for both users and developers
- **Backward Compatibility**: Added note about maintaining compatibility …
> Update SECURITY.md and complete LICENSE file with proper ViewTouch information

- changelog.md
- print/print_main.cc
- Fix critical bug: Remove debug exit(2) that prevented program execution
- Modernize C++ includes: Use <cstring>, <csignal>, <vector> instead of C headers
- Enhance buffer management: Replace raw char arrays with std::vector<char>
- Add graceful shutdown: Signal handlers for SIGINT/SIGTERM with proper cleanup
- Improve error handling: Better validation, resource management, and error reporting
- Add const correctness: Improve parameter passing and variable initialization
- Enhance input validation: Port number range checking (1-65535) and argument parsing
- Ensure resource safety: Proper file descriptor management and cleanup
- Better data flow: Enhanced handling of partial writes and connection states
- Maintain full backward compatibility with existing functionality
All changes tested …
> Modernize vt_print daemon with C++20 improvements and critical bug fixes

- changelog.md
- main/manager.cc
- socket.cc
- term/term_view.cc
- term/term_view.hh
- vt_ccq_pipe.cc
- zone/button_zone.cc
> Fix Editor Settings Save Issue and Add Comprehensive Null Pointer Protection

- cdu/cdu_main.cc
- changelog.md
- term/layer.cc
- term/term_view.cc
- term/term_view.hh
- zone/table_zone.cc
This PR introduces a comprehensive dynamic scaling system that allows ViewTouch to adapt seamlessly to any display resolution, along with critical bug fixes and code modernization improvements.
- Add comprehensive scaling system with 1920x1080 as universal reference
- Implement CalculateScaleFactors(), ScaleX/Y/W/H(), and ScaleFontSize() functions  
- All UI elements now scale proportionally for ultra-wide, 4K, and portrait displays
- Universal page template system uses PAGE_SIZE_1920x1080 for all displays
- Server always receives consistent 1920x1080 dimensions regardless of screen size
- Remove hardcoded MAX_SCREEN_WIDTH/HEIGHT limits for better compatibility
- Add X11 compatibility limits (4096x4096 max) for XServer XSDL support
- Fonts, buttons, zones scale smoothly while maintaining …
> Universal Dynamic Scaling System & UI Improvements

- docs/changelog.md
- src/core/error_handler.cc
- src/core/error_handler.hh
- term/layer.cc
- term/term_view.cc
- term/term_view.hh
This PR modernizes the unified error handling framework (`error_handler.hh/cc`) to leverage modern C++17/20 features while maintaining 100% backward compatibility with existing code.
- **Modern Includes**: Added `string_view`, `shared_mutex`, `once_flag`, `optional`, `span`, `cstdint`
- **Enum Improvements**: Used `std::uint8_t` as underlying type for better memory efficiency
- **String Handling**: Replaced `const std::string&` with `std::string_view` for zero-copy operations
- **Thread Safety**: Upgraded from `std::mutex` to `std::shared_mutex` for concurrent read access
- **Singleton Pattern**: Modernized with `std::once_flag` instead of manual mutex locking
- **Rule of Five**: Explicitly defined copy/move semantics with deleted copy operations
- **Constexpr Functions**: Made utility …
> Modernize Error Handler with C++17/20 Features
