term/term_view.cc

On Debian Jessie (and possibly other distributions) this eliminates the need for the /usr/viewtouch/fonts/ directory, while still maintaining compatibility with the Android app.
The Android app still works just fine, but this change eliminates the need for the fonts directory.
My system, a fairly minimal install of Debian with only:
Debian Desktop Environment
LXDE
SSH
Base System Utils
and the packages installed in the "Building" wiki page has fonts that appear to have an identical name and functionality to the fonts included with ViewTouch, only difference is that ViewTouch expects the fonts to end with -15 while my system's fonts end in -1. This change enables both fonts to work.
I have tested this with the Android app connecting to my PC running ViewTouch, PC without the ViewTouch …

Enable Out-Of-Box Fonts to work

---

CMakeLists.txt

declare the GTK3 header includes as system library. We can't fix those
warnings, so don't show them

cmake: include GTK3 headers as system library

---

.travis.yml
README.md
ci/Dockerfile.debian.template
ci/Dockerfile.ubuntu.template
ci/toolchains/.gitignore
ci/toolchains/default.cmake
ci/toolchains/gcc-cxx11.cmake
ci/toolchains/gcc-cxx14.cmake
ci/toolchains/gcc-cxx17.cmake
ci/toolchains/gcc-cxx98.cmake
ci/toolchains/gcc-gnuxx11.cmake
ci/travis.debian.sh
ci/travis.ubuntu.sh

use travis-ci to build viewtouch on Ubuntu and Debian
also adds a Build-Tag with the latest build status
travis-ci needs to be enabled for this to take an effect: https://github.com/ViewTouch/viewtouch/issues/23

Add Continuous Integration

---

conf_file.cc
conf_file.hh
main/settings.cc

- explizitly use std:: namespace, no using std
conf_file.hh and conf_file.cc:
- use ofstream and ifstream
use outputfilestream instead of more generic filesteam. WriteLn only
outputs to a file. It would make no sense to read from a file in WriteLn
- use constexpr instead of macro define
- use default initializers for structs
- use const references for most passed parameter
- make GetKey and GetSection const (does not modify internal data
structure)
- use const references for passed parameter
- fix memory leak: no need to create a object with new when passing it
to std::vector
- cerr understands std::string
- cleanup Load()
- for sections just look at the first character if it is '[', no need to
search the whole string
- don't store the current section, just the current section-name
- …

Modernize conf file

---

CMakeLists.txt

- don't overwrite CXX flags, instead append new flags
- add shadowing and conversion warnings
this fixes starting the debugger and set breakpoints out of qtcreator. it seems that the `-g` flag was not set because the CMAKE_CXX_FLAGS_DEBUG was overwritten
https://stackoverflow.com/questions/5179202/gcc-g-what-will-happen#5179230

cmake: fix CXX flag setting

---

CMakeLists.txt

This does not change the compiled binaries. The only difference is, that
the header files are listed with the respective targets in the IDE.
- add zone headers to target
- add vt_main headers to target
- add vtcore headers to target

cmake: explicitly add header files to target

---

.travis.yml

with this commit in the Language category for the CI jobs at travis there stands "C++" instead of "no language set"

ci: set language to cpp

---

CMakeLists.txt

force the public cache variable CMAKE_INSTALL_PREFIX to be set if user
did not set it

cmake: fix setting of install prefix

---

zone/report_zone.cc

for revenue report a period of SP_NONE is not handled, but is returned
after SP_YTD. Fixing it by cycling around to SP_DAY
@GeneMosher please test if this fix breaks other report functionality
fixes https://github.com/ViewTouch/viewtouch/issues/60

zone: fix revenue report period cycling

---

main/terminal.cc
main/terminal.hh

fix a rare segfault for `RemoveTimeOutFn` call when repeatedly clicking
buttons
fixes https://github.com/ViewTouch/viewtouch/issues/61

main: add mutex for redraw_id

---

main/labor.cc

apply the same check for start variable as for end variable

main: check start variable in Overlap calculation

---

main/manager.cc

The month June was two times in the list of month shortnames
This fixes the clock on the start page

main: manager: fix double mention of short month

---

main/system_report.cc

check for validity of time_was before equal comparison

fix system report for exceptional transactions

---

main/sales.cc

FilterName did make a copy of the original string before adding the new
string with reduced whitespaces

main: fix duplication of new menu item names

---

main/check.cc

fix segfault on finishing an order if no printer is present

main: check: don't access printer when it is a nullptr

---

main/manager.cc

UpdateID was an int, Xt timer is an unsigned long. If a timer with
values bigger than int-max is returned the XtRemoveTimeOut segfaults
during shutdown.

main: manager: fix shutdown crash

---

changelog.md
main/manager.cc
main/manager.hh
main/terminal.hh

`input_id` was an int, XtInputId is an unsigned long. If an input_id with
values bigger than int-max is returned the XtRemoveInput segfaults.

Fix input_fn type

---

changelog.md
main/settings.cc

fixes regression introduced in 7e4abf7
This commit introduced a `std::runtime_error` if the `conf_file` does not
exist. This error was not caught. Check for existence before opening
file.

Handle conf file exception

---

changelog.md
main/report.cc
zone/report_zone.cc

don't render reports that failed to load. This resulted in an empty body_list which was not handled by Report::Render. Be more careful on both sides
fixes https://github.com/ViewTouch/viewtouch/issues/89

Fix failed report render

---

changelog.md
loader/loader_main.cc

- load CSS from hard coded string instead of vtpos.css file
- fix Gtk deprecation warnings regarding the font selection
- fix logofile path to work in different install targets

Fix loader css loading

---

changelog.md
main/manager.cc

disable auto update as there is no file provided to download. Disabling
the updater gets rid of another unneeded warning during startup

main: manager: disable autoupdate

---

changelog.md
zone/payment_zone.cc

in training mode the receipt when finalizing a payment was not printed. Do we want it to be printed even in training mode or is this behavior intended?

Print receipt in training mode

---

changelog.md
utility.cc
utility.hh

the original utility::StringCompare function compared only the same
length part of the string. I did not reimplement the functionality
right and compared the full strings
old behavior:
StringCompare("print subcheck", "print") == 0 (it compares equals)
my wrongly implemented behavor:
std::string("print subcheck") .compare(std::string("print")) == 1
(not comparing equal)

Fix StringCompare

---

CMakeLists.txt
ci/travis.sh

test install target because `dat` folder is missing in source, which breaks the install target
https://github.com/ViewTouch/viewtouch/issues/101
don't yet merge, I need to first fix the `CMakeLists.txt` entry to detect the `dat` folder and handle the case it is missing

handle missing dat folder and add install target

---

CMakeLists.txt
changelog.md
data_file.cc
tests/data_file/test_data_file.cc
tests/main/CMakeLists.txt
tests/main/manager_stub.cc
tests/main/test_labor.cc
tests/main/test_main.cc
tests/time_info/test_time_info.cc

The bug was caused by the unhandled case of an uninitialized TimeInfo written
to a file and read back. The read back version was initialized to 0 sec in year
1970. The `LaborDB::IsUserOnClock()` checks the end `TimeInfo` to be uninizialized.
With this bug the employee is never clocked in after a restart of ViewTouch.
Fix this by writing out non-set `TimeInfo` values as `sec==0` `year==0`, and
handle them accordingly in the `Read(TimeInfo)` function.
Add tests for `TimeInf`o and a regression test for this bug to never again
creep in unnoticed.
Fixes: https://github.com/ViewTouch/viewtouch/issues/108
@GeneMosher  please test if my claims are indeed valid
```sh
git fetch
git checkout fix_clock_in_again
```

Handle non-set TimeInfo Read/Write fixing Clock In bug

---

changelog.md
main/report.cc
main/report.hh
tests/main/CMakeLists.txt
tests/main/test_report.cc

In 9f10c00e461f6b86c8f9c2f9c058698df228efc7 main: report: remove custom DList, updates
the `Report::Text` function was switched to accept `std::string&` instead
of `const char*`. In the conversion the possibility of the char ptr to
be a nullptr was forgotten. A nullptr for text is interpreted as
`draw_a_line`. As `std::string` has no distinction between nullptr and
an empty string introduce the variable `bool draw_a_line` and
reintroduce the `const char*` overloads for `Report::Text` and
`ReportEntry()`.
Add tests to check ReportEntry constructors with `const char *` and
`std::string`. Especially the new behavior when `nullptr` is passed as
text, which should be the only instance `draw_a_line` should be set to
true.
fixes: https://github.com/ViewTouch/viewtouch/issues/115

main: report: Handle nullptr const char ptr in Report::Text again

---

CMakeLists.txt
main/manager.cc

Otherwise `curlcpp` downloads an html redirect page looking as follows:
```html
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="https://viewtouch.com/vt_data">here</a>.</p>
</body></html>
```
and we get error messages when starting `vtpos`
```
Trying VT_DATA: /usr/viewtouch/dat/vt_data
Unable to read non existing file: '/usr/viewtouch/dat/vt_data'
Trying download VT_DATA: /usr/viewtouch/bin/vt_data from 'http://www.viewtouch.com/vt_data'
Successfully downloaded file '/usr/viewtouch/bin/vt_data' from 'http://www.viewtouch.com/vt_data'
Unknown file format for file: '/usr/viewtouch/bin/vt_data'
Unable to find vt_data file!!!
```

Update vt_data download url from http to https

---

changelog.md
main/manager.cc
tests/main/manager_stub.cc

First found for `vt_data` and fixed with
https://github.com/ViewTouch/viewtouch/pull/151
Fixing `tables.dat`, `menu.dat` and `zone_db.dat` URLs as well.

manager.cc: fix download URLs for bootstrap dat files

---

CMakeLists.txt
changelog.md

Require a CMake 3.25.1 minimum version (version used by Debian 12 bookworm).
This fixes a CMake error when configuring with CMake 4.0+:
```
CMake Error at external/date/CMakeLists.txt:1 (cmake_minimum_required):
Compatibility with CMake < 3.5 has been removed from CMake.
Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
to tell CMake that the project requires at least <min> but has been updated
to work with policies introduced by <max> or earlier.
Or, add -DCMAKE_POLICY_VERSION_MINIMUM=3.5 to try configuring anyway.
```
Fixes: https://github.com/ViewTouch/viewtouch/issues/156

cmake: fix deprecation warning, CMake 4.0+ compatibility

---

changelog.md
main/terminal.cc
zone/zone.cc

- Fix button deselection when clicking in open areas
- Ensure proper screen refresh on selection changes
- Fix multi-select behavior to clear previous selections
- Improve drag selection with Shift key support
- Add proper deselection when clicking open areas
- Update changelog with all UI improvements

Improve UI selection and refresh behavior in edit mode

---

CMakeLists.txt
changelog.md
main/employee.cc
main/manager.cc
main/terminal.cc
term/term_dialog.cc
term/term_view.cc
zone/form_zone.cc
zone/layout_zone.cc
zone/phrase_zone.cc
zone/phrase_zone.hh

This pull request resolves multiple UI rendering and layout issues caused by uninitialized or incorrect font metric values. The changes primarily affect the Customize Job Titles, Families, Phrases (PhraseZone), and LayoutZone classes.
🔧 Fixes and Improvements
Customize Zone (Job Titles, Families, Phrases):
Fixed layout so each entry field appears on its own line.
Corrected sizing of entry fields for better readability and usability.
LayoutZone (UI Rendering & Font Metrics):
Added validation to ensure font metrics are initialized before rendering.
Prevented division-by-zero errors during font metric calculations.
Corrected layout calculations for:
Zone sizing
Margins and padding
UI element positioning
Fixed spacing in employee lists to prevent names from stacking.
Resolved text alignment …

Fix UI Layout and Font Metric Issues Across Customize and Layout Zones

---

.github/workflows/linux-simple-builds.yml
CMakeLists.txt
changelog.md
error_handler.cc
error_handler.hh
font_check.cc
generic_char.cc
loader/loader_main.cc
main/manager.cc
main/manager.hh
main/remote_printer.cc
main/settings.cc
main/settings.hh
main/system.cc
main/system.hh
main/system_report.cc
main/terminal.cc
main/terminal.hh
remote_link.cc
remote_link.hh
string_utils.cc
string_utils.hh
zone/creditcard_list_zone.cc
zone/settings_zone.cc

This pull request modernizes the **ViewTouch** codebase, upgrading from **C++17 → C++20** with major improvements in **memory safety, string handling, and build system configuration**.  
The changes maintain **full backward compatibility** while providing a **future-ready foundation**.  
---
- ✅ 280+ raw pointers → Smart pointer management (RAII)  
- ✅ 50+ sprintf calls → Bounds-checked snprintf  
- ✅ C-style arrays → Modern STL containers (std::vector, std::array)  
- ✅ Manual memory cleanup → Automatic RAII management  
- ✅ C++20 build system with stricter compiler warnings  
- ✅ New infrastructure for string utilities & error handling  
---
- RemotePrinter: Raw new/delete → std::unique_ptr & std::make_unique  
- System: Modernized credit card database pointers with std::unique_ptr  
- …

🚀 Comprehensive C++20 Modernization and Safety Improvements

---

changelog.md
zone/report_zone.cc

This pull request implements enhanced kitchen and bar video display separation with order recall functionality, providing complete independence between departments while maintaining proper order tracking and recall capabilities.
- **Independent Status Tracking**: Implemented separate check flags for kitchen and bar video displays
-  (16): Kitchen marks their portion as made/ready
-  (32): Bar marks their portion as made/ready  
-  (64): Kitchen marks their portion as served
-  (128): Bar marks their portion as served
- **First Tap**: Marks order as "made" for that video target only
- **Second Tap**: Marks order as "served" for that video target only  
- **Target-Specific Recall**: Finds most recent check served by current video target
- **Smart Order Recovery**: Recalls order by clearing …

Enhanced Kitchen and Bar Video Display Separation with Order Recall

---

changelog.md
main/labels.cc
main/manager.cc
main/settings.cc
main/settings.hh
zone/order_zone.cc
zone/pos_zone.cc
zone/settings_zone.cc

This PR extends Editor user permissions to customize the Order Entry Button size and position, adds persistent storage of custom settings, and implements user control over automatic system updates.
- Editor users (id == 2) could not edit the Order Entry Button size/position
- Custom size changes were not being saved to the system data file
- Automatic `vt_data` downloads would overwrite custom settings
- No user control over when system updates occur
1. **Extended Editor Permissions**: Modified `PosZone::CanEdit()` and `PosZone::CanCopy()` to allow Editor access to `ZONE_ORDER_ENTRY` zones
2. **Persistent Storage**: Added `SaveSystemData()` calls in `OrderEntryZone::SetSize()` and `OrderEntryZone::SetPosition()` methods
3. **Auto-Update Control**: Implemented "Auto-Update vt_data on …

Editor Access to Order Entry Button Customization with Persistent Storage

---

changelog.md
main/manager.cc
main/terminal.cc
term/term_view.cc
term/term_view.hh
zone/order_zone.cc

- Fixed Editor Order Entry Changes Not Saving:
* Modified EditTerm() to always call SaveSystemData() for all users
* Enhanced EndSystem() and ExecuteRestart() to save pending changes before shutdown
* Order Entry window changes now persist across program restarts for both Editors and Super Users
- Fixed System Hang Issues:
* Resolved infinite ppoll() loop in vt_term with invalid file descriptors
* Added robust socket error handling and reconnection logic
* Enhanced main event loop with proper error handling and graceful exit conditions
* Fixed Order Entry zone null pointer checks to prevent segfaults
- Improved Order Entry Permissions:
* Editors can now save Order Entry changes immediately (not just mark as pending)
* Simplified permission logic to allow both user types to save changes
* …

Fix Editor Order Entry Save Issues and System Hang Problems

---

changelog.md
data_persistence_manager.cc
main/manager.cc
scripts/vtrestart
term/term_view.cc

- Fixed segmentation fault in XtRemoveInput() during X11 resource cleanup
- Added proper validation and error handling for all XtRemoveInput() calls
- Enhanced RemoveInputFn() with App context validation in manager.cc
- Added try-catch blocks around XtRemoveInput() calls in term_view.cc
- Ensured input IDs are properly reset to 0 after removal
- Added error logging for invalid Xt context scenarios
- Updated changelog.md with detailed fix documentation
This resolves the issue where 'Refresh ViewTouch' would hang on 'Shutting Down' and prevents system restart commands from working properly. The restart functionality now works correctly without hanging or crashing.

Fix: Resolve 'Refresh ViewTouch' hanging issue

---

changelog.md
main/check.cc
main/check.hh
main/terminal.cc
version.cmake

This pull request includes 3 commits that enhance the SelfOrder functionality and fix critical backward compatibility issues.
- **Fixed check type constants renumbering issue** that was causing data corruption
- Restored original values for \`CHECK_DINEIN\` (11), \`CHECK_TOGO\` (12), \`CHECK_CALLIN\` (13)
- Reassigned \`CHECK_SELFDINEIN\` (14) and \`CHECK_SELFTAKEOUT\` (15) to avoid conflicts
- **Prevents data corruption** from existing saved checks with old type values
- Added \`CHECK_SELFDINEIN\` and \`CHECK_SELFTAKEOUT\` check types for proper differentiation
- Implemented \`IsSelfDineIn()\` and \`IsSelfTakeOut()\` methods in Check class
- Updated related methods (\`IsSelfOrder()\`, \`IsTakeOut()\`, \`IsForHere()\`, \`IsToGo()\`) for consistency
- Fixed 'No Drawer Available' issue by …

SelfOrder Mode Enhancements and Critical Bug 

---

src/utils/string_utils.cc

This PR fixes the \`parse_price\` function in \`string_utils.cc\` to properly handle currency symbols in various formats.
- Improved handling of currency symbols (\$) that can appear before or after negative signs (e.g., \"\$-12.34\" or \"-\$12.34\")
- Fixed sign extraction to work correctly regardless of currency symbol position
- Removed old sequential character-by-character approach in favor of a more robust solution using \`std::remove\`
- Added support for both '+' and '-' sign prefixes
- \`src/utils/string_utils.cc\`: Updated \`parse_price\` function logic
The fix ensures that price strings with currency symbols are correctly parsed regardless of where the currency symbol appears in relation to the sign.

Fix parse_price handling of currency symbols

---

docs/changelog.md
main/data/manager.cc

- Fixed critical issue where printers were being duplicated after restart
- Root cause: System was creating new 'Report Printer' entries on every startup without checking if one already existed
- Solution: Added duplicate check using settings->FindPrinterByType(PRINTER_REPORT) before creating new report printers
- Modified report printer creation logic in StartSystem() function to reuse existing printers
- Result: Only one report printer is created and maintained across multiple restarts
- Files modified: main/data/manager.cc - Enhanced printer initialization with duplicate prevention
- Impact: Eliminates printer duplication in settings, maintains clean configuration files

Fix printer duplication bug after ViewTouch restart

---

SECURITY.md
docs/changelog.md
zone/button_zone.cc

This PR includes a critical fix for self-order button functionality and updates the security documentation to reflect the current release version.
**Problem:** The `quickdinein` and `quicktogo` buttons on the self-order page were not working correctly because they were calling the wrong check types.
**Solution:**
- Fixed `MessageButtonZone::Signal()` to use correct self-order check types
- `quickdinein` now calls `CHECK_SELFDINEIN` instead of `CHECK_DINEIN`
- `quicktogo` now calls `CHECK_SELFTAKEOUT` instead of `CHECK_TOGO`
- Self-order buttons now properly differentiate between dine-in and take-out orders
- Updated changelog.md with fix details
**Files Modified:**
- `zone/button_zone.cc` - Fixed message handling logic
- `docs/changelog.md` - Added documentation for the fix
- Merged …

Self-Order Button Fix and Security Update
